// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/campaigns" | "/dashboard/clients" | "/dashboard/meta-connect" | "/dashboard/reports" | "/dashboard/settings" | "/forgot-password" | "/login" | "/reset-password" | "/signup" | "/view/[token]"
type AppRouteHandlerRoutes = "/api/ad-accounts" | "/api/auth/[...nextauth]" | "/api/auth/facebook" | "/api/auth/facebook/callback" | "/api/auth/forgot-password" | "/api/auth/register" | "/api/auth/reset-password" | "/api/campaign-insights/[campaignId]" | "/api/campaigns/[accountId]" | "/api/clients" | "/api/dashboard/overview" | "/api/generate-share-link" | "/api/shared-campaign/[token]" | "/api/user/profile"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ad-accounts": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/facebook": {}
  "/api/auth/facebook/callback": {}
  "/api/auth/forgot-password": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/campaign-insights/[campaignId]": { "campaignId": string; }
  "/api/campaigns/[accountId]": { "accountId": string; }
  "/api/clients": {}
  "/api/dashboard/overview": {}
  "/api/generate-share-link": {}
  "/api/shared-campaign/[token]": { "token": string; }
  "/api/user/profile": {}
  "/dashboard": {}
  "/dashboard/campaigns": {}
  "/dashboard/clients": {}
  "/dashboard/meta-connect": {}
  "/dashboard/reports": {}
  "/dashboard/settings": {}
  "/forgot-password": {}
  "/login": {}
  "/reset-password": {}
  "/signup": {}
  "/view/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
