// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type { NextRequest } from "next/server.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any,
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>,
      ) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>);
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  POST?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  PUT?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  PATCH?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  DELETE?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  HEAD?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  OPTIONS?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
};

// Validate ../../src/app/dashboard/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/campaigns">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/campaigns/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clients">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/clients/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/meta-connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/meta-connect">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/meta-connect/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/reports/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific;
  const handler = {} as typeof import("../../src/app/forgot-password/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific;
  const handler = {} as typeof import("../../src/app/login/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
  const handler = {} as typeof import("../../src/app/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific;
  const handler = {} as typeof import("../../src/app/reset-password/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific;
  const handler = {} as typeof import("../../src/app/signup/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/view/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/view/[token]">> = Specific;
  const handler = {} as typeof import("../../src/app/view/[token]/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/ad-accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ad-accounts">> = Specific;
  const handler = {} as typeof import("../../src/app/api/ad-accounts/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific;
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/auth/facebook/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/facebook/callback">> = Specific;
  const handler = {} as typeof import("../../src/app/api/auth/facebook/callback/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/auth/facebook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/facebook">> = Specific;
  const handler = {} as typeof import("../../src/app/api/auth/facebook/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific;
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific;
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific;
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/campaign-insights/[campaignId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaign-insights/[campaignId]">> =
    Specific;
  const handler = {} as typeof import("../../src/app/api/campaign-insights/[campaignId]/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/campaigns/[accountId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[accountId]">> = Specific;
  const handler = {} as typeof import("../../src/app/api/campaigns/[accountId]/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific;
  const handler = {} as typeof import("../../src/app/api/clients/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/dashboard/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/overview">> = Specific;
  const handler = {} as typeof import("../../src/app/api/dashboard/overview/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/generate-share-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-share-link">> = Specific;
  const handler = {} as typeof import("../../src/app/api/generate-share-link/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/shared-campaign/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shared-campaign/[token]">> = Specific;
  const handler = {} as typeof import("../../src/app/api/shared-campaign/[token]/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific;
  const handler = {} as typeof import("../../src/app/api/user/profile/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific;
  const handler = {} as typeof import("../../src/app/dashboard/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import("../../src/app/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
